//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client2.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IDriveSpace")]
    public interface IDriveSpace {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDriveSpace/FreeSpace", ReplyAction="http://tempuri.org/IDriveSpace/FreeSpaceResponse")]
        string FreeSpace(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDriveSpace/FreeSpace", ReplyAction="http://tempuri.org/IDriveSpace/FreeSpaceResponse")]
        System.Threading.Tasks.Task<string> FreeSpaceAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDriveSpace/TotalSpace", ReplyAction="http://tempuri.org/IDriveSpace/TotalSpaceResponse")]
        string TotalSpace(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDriveSpace/TotalSpace", ReplyAction="http://tempuri.org/IDriveSpace/TotalSpaceResponse")]
        System.Threading.Tasks.Task<string> TotalSpaceAsync(string str);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDriveSpaceChannel : Client2.ServiceReference1.IDriveSpace, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DriveSpaceClient : System.ServiceModel.ClientBase<Client2.ServiceReference1.IDriveSpace>, Client2.ServiceReference1.IDriveSpace {
        
        public DriveSpaceClient() {
        }
        
        public DriveSpaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DriveSpaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DriveSpaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DriveSpaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string FreeSpace(string str) {
            return base.Channel.FreeSpace(str);
        }
        
        public System.Threading.Tasks.Task<string> FreeSpaceAsync(string str) {
            return base.Channel.FreeSpaceAsync(str);
        }
        
        public string TotalSpace(string str) {
            return base.Channel.TotalSpace(str);
        }
        
        public System.Threading.Tasks.Task<string> TotalSpaceAsync(string str) {
            return base.Channel.TotalSpaceAsync(str);
        }
    }
}
